### ISSUE TITLE
Identical deployments in different namespaces

### ISSUE THREAD

**Issue by anton-johansson** [kubernetes-incubator/descheduler#147]
I have two identical statefulsets (would be the same for deployment too, I suppose), in two different namespaces. They have the same name of the set, same name of the service, and they have the same labels.

They both work in terms of "pure" k8s. They control their own three pods, respectively.

However, one of the sets keep getting evicted by descheduler. I assume the descheduler does not consider namespace of the pods? Is this intended?

**Comment by anton-johansson** [comment]
https://github.com/kubernetes-incubator/descheduler/blob/fc1688057aecc30dceb4d67c5b270446f32b02a9/pkg/descheduler/strategies/duplicates.go#L92

This is probably the cause of it. Can't we use the `ownerReferences[].uid` instead of `ownerReferences[].kind + ownerReferences[].name`?

**Comment by tammert** [comment]
@anton-johansson , we were having the same issue and I can confirm your solution of using `ownerRef.UID` instead of `ownerRef.Kind + ownerRef.Name` fixes this just nicely! Thanks for that.

I'm not affiliated to this project though, so you might want to check with @aveshagarwal if he would accept a pull request for this. FYI, just using `ownerRef.UID` makes for much vaguer log messages, so you might want to keep that in mind (maybe _add_ the UID to the string instead of replacing it).

**Comment by aveshagarwal** [comment]
@anton-johansson @tammert please feel free to submit a PR as that sounds like an issue.

**Comment by tammert** [comment]
@anton-johansson let me know if you want to make a PR, otherwise I'll be happy to contribute it!

**Comment by anton-johansson** [comment]
@tammert, I would love to, but I don't see myself having the time for it as of right now. Feel free to work on it!

Sorry for the delayed response.

**Comment by tammert** [comment]
@anton-johansson no worries, glad you responded! I've created the PR for @aveshagarwal to review: PR #156.
